pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:

  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - sh
    - -c
    - sleep 999999
    tty: true

  - name: deploy
    image: alpine:3.19
    command:
    - sh
    - -c
    - sleep 999999
    tty: true
"""
    }
  }

  stages {

    stage('Build & Push Image') {
      steps {
        container('kaniko') {
          withCredentials([usernamePassword(
            credentialsId: 'dockerhub',
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PASS'
          )]) {
            sh '''
              mkdir -p /kaniko/.docker
              cat > /kaniko/.docker/config.json <<EOF
              {
                "auths": {
                  "https://index.docker.io/v1/": {
                    "username": "${DOCKER_USER}",
                    "password": "${DOCKER_PASS}"
                  }
                }
              }
EOF

              /kaniko/executor \
                --dockerfile=app/Dockerfile \
                --context=app \
                --destination=sridevi1902/flask-app:latest
            '''
          }
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        container('deploy') {
          sh '''
            apk add --no-cache curl bash

            curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
            chmod +x kubectl
            mv kubectl /usr/local/bin/

            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml
            kubectl rollout status deployment/flask-app
          '''
        }
      }
    }
  }
}
