pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - sh
    - -c
    - sleep 999999
    tty: true

  - name: kubectl
    image: bitnami/kubectl:1.30
    command:
    - sh
    - -c
    - sleep 999999
    tty: true
"""
    }
  }

  stages {

    stage('Build & Push Image') {
      steps {
        container('kaniko') {
          withCredentials([usernamePassword(
            credentialsId: 'dockerhub',
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PASS'
          )]) {
            sh '''
              mkdir -p /kaniko/.docker
              cat > /kaniko/.docker/config.json <<EOF
              {
                "auths": {
                  "https://index.docker.io/v1/": {
                    "username": "${DOCKER_USER}",
                    "password": "${DOCKER_PASS}"
                  }
                }
              }
EOF

              /kaniko/executor \
                --dockerfile=app/Dockerfile \
                --context=app \
                --destination=sridevi1902/flask-app:latest
            '''
          }
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        container('kubectl') {
          dir("${WORKSPACE}") {
            sh '''
              echo "Deploying application..."
              kubectl apply -f k8s/deployment.yaml
              kubectl apply -f k8s/service.yaml
              kubectl rollout status deployment/flask-app
            '''
          }
        }
      }
    }
  }
}
